### ISSUE TITLE
How to push the finetuned Mistral model to HF hub?

### ISSUE THREAD

**Issue by elliotthwang** [brevdev/notebooks#5]
Thank you for your notebook" Fine-tuning Mistral on your own data".
However once finetuned the model by our own data,
how to push the finetuned Mistral model to HF hub?

Thanks!
@

**Comment by npastrami** [comment]
I am here wondering the same thing ^^

**Comment by kaushalpowar** [comment]
@elliotthwang @npastrami 

 `# Push to HF Hub.   `  


`merged_model.push_to_hub('username/model_card_name')`
`tokenizer.push_to_hub('username/model_card_name')`

Make sure to create a new model card on huggingface first.
In order to push model to HF you have to pass your write token from Huggingface, you can find it [here](https://huggingface.co/settings/tokens)

`!huggingface-cli login --token hf_Y`
